name: Deploy GiriPet API to IIS via FTP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Install EF Core Tools
      run: dotnet tool install --global dotnet-ef

    - name: Add EF tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Run EF Core migrations
      run: dotnet ef database update --project GiriPet.Data/GiriPet.Data.csproj --startup-project GiriPet.Api/GiriPet.Api.csproj

    - name: Publish API
      run: dotnet publish GiriPet.Api/GiriPet.Api.csproj -c Release -o ./publish

    - name: FTP Deploy to VDS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.VDS_HOST }}
        username: ${{ secrets.VDS_USER }}
        password: ${{ secrets.VDS_PASSWORD }}
        port: ${{ secrets.VDS_PORT }}
        local-dir: ./publish
        server-dir: ${{ secrets.VDS_TARGET_PATH }}
